export let users = [
	{
		id: '1',
		fullname: 'Ахмадиев Фаризулла Мухаммадиевич',
		statuses: ['Руководитель отделения', 'Член правления ВООПИК'],
		mainStatus: 'Первый статус',
		mainDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar sic tempor. Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus pronin sapien nunc accuan eget.',
		birthday: '1981.10.17',
		position: 'Руководитель Отделения',
		group: 'Правление',
		regDate: '2010.12.23',
		locality: 'Россия, Тамбовская обл., Сосновский р-н, с. Атманов Угол',
		gender: 'Мужской',
		phones: ['+7 (432) 900-00-00', '+7 (917) 310-09-08'],
		email: 'tatartstan@voopik.ru',
		website: 'www.example.com/konstantinopolskiy'
	},
	{
		id: '2',
		fullname: 'Кленовичичевский Богдан Архедупсович',
		statuses: ['Руководитель отделения', 'Член правления ВООПИК'],
		mainStatus: 'Второй статус',
		mainDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar sic tempor. Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus pronin sapien nunc accuan eget.',
		birthday: '1977.09.11',
		position: 'Секретарь Отделения',
		group: 'Правление',
		regDate: '2005.02.15',
		locality: 'Россия, Тамбовская обл., г. Тамбов',
		gender: 'Мужской',
		phones: ['+7 (432) 923-11-18', '+7 (917) 410-05-08'],
		email: 'bogdan@voopik.ru',
		website: 'www.example.com/arch'
	},
	{
		id: '3',
		fullname: 'Нифаригуллина Мавлюда Талгатовна',
		statuses: ['Руководитель отделения', 'Член правления ВООПИК'],
		mainStatus: 'Третий статус',
		mainDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar sic tempor. Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus pronin sapien nunc accuan eget.',
		birthday: '1992.08.11',
		position: 'Участник',
		group: 'Участники',
		regDate: '2004.03.11',
		locality: 'Россия, Тамбовская обл., г. Тамбов',
		gender: 'Женский',
		phones: ['+7 (432) 900-01-01', '+7 (917) 210-03-08'],
		email: 'mavluda@voopik.ru',
		website: 'www.example.com/mavluda'
	},

]